require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - 'db/seeds.rb'

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'app/views/**/*'

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - spec/support/*

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*.rb

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*
    - spec/system/**/*

RSpec/NotToNot:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
  - spec/system/**/*

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Naming/VariableNumber:
  Exclude:
  - spec/**/*.rb
